const domain = "/imgs/";
export default {
      linjia : domain + "icon-linjiabiaoqian.png",
      lintiao : domain + "icon-lintiaobiaoqian.png",
      buke : domain + "icon-bukebiaoqian.png",
      qiandao : domain + "icon-qiandaobiaoqian.png",
      qingjia : domain + "icon-qingjiabiaoqian.png",
      gou : domain + "icon-paixugouxuan.png",
      jiang : domain+"icon-jiangxu.png",
      sheng : domain+"icon-shengxu.png",
      jiang1 : domain+"icon-danchuang-jiangxu.png",
      sheng1 : domain+"icon-danchuang-shengxu.png",
      arrowRight : domain + "icon-youjiantou.png",
      checkBox : domain + "icon-duoxuan.png",
      jinzhi : domain + "icon-jinzhi.png",
      guoqi : domain + "icon-guoqitishi.png",
      deleteStu : domain + "icon-shanchuxueyuan.png",
      telephone : domain + "icon-bodadianhua.png",
      queqin: domain + "icon-queqin.png",
      queqin2 : domain + "icon-queqinyixuan.png",
      triangle : domain + "icon-sanjiaoxing1.png",
      triangle2 : domain + "icon-sanjiaoxing2.png",
      unCheckBox : domain + "icon-duoxuan-weixuanze.png",
      search :  domain + "icon-sousuo1.png",
      sortAsc : domain + "icon-qian.png",
      sortDesc : domain + "icon-hou.png",
      arrowLeft : domain + "icon-zuobianjiantou.png",
      triangle1 : domain + "icon-sanjiaoxing.png",
      jiaoshi : domain + "icon-jiaoshi1.png",
      teacher : domain + "icon-laoshi.png",
      weishangke : domain + "icon-weishangke.png",
      yishangke : domain + "icon-yishangke.png",
      empty001 : domain + "001.png",
      empty1001 : domain + "1001.png",
      weixuanze : domain + "icon-danxuan-weixuanze.png",
      yixuanze : domain + "icon-danxuan.png",
      exitlogo : domain + "exitlogo.png",
      loginlogo : domain + "loginlogo.png",
      authlogo : domain + "authlogo.png",
      yonghumingicon : domain + "icon-yonghumingicon.png",
      mimaicon : domain + "icon-mimaicon.png",
      xianshi : domain + "icon-xianshi.png",
      buxianshi : domain + "icon-buxianshi.png",
      roleup : domain + "icon-xuanzeshenfen-shang.png",
      roledown : domain + "icon-xuanzeshenfen-xia.png",
      upicon : domain + "icon-up.png",
      downicon : domain + "icon-down.png",
      userdelete : domain + "user-delete.png",
      kuakecheng: domain + "icon-kuakecheng.png",
      addPic: domain + "icon-addpic.png",
}